spring:
  application:
    name: demo_ForMybatisPlus
#  datasource:
#
#    url: jdbc:sqlite:D:/桌面/Desktop/学习/javalearn/javaWeb/tasks/src/main/resources/tasks.sqlite3
#    url: jdbc:sqlite:/opt/tasks.sqlite3
#
#    driver-class-name: org.sqlite.JDBC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.94.234.64:3306/tasks
    username: tasks
    password: 123456

mybatis-plus:

  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.ssmlearn.tasks.generator.pojo
